[project]
name = "ifactory-cmms-deploy"
version = "0.1.0"
requires-python = ">=3.12,<3.13"
dependencies = []

[project.scripts]
cmms-development = "ifactory_cmms_deploy.cli:main"

[build-system]
requires = ["hatchling==1.27.0"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/ifactory_cmms_deploy"]
